spring.application.name=ticketmanagement

spring.datasource.url=jdbc:postgresql://localhost:5433/telco_ticket_db
spring.datasource.username=telco
spring.datasource.password=telco123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=telcocare-ticket-management-super-secret-key-2026-very-secure
jwt.expiration=86400000